In [2]:
import numpy as np

In [25]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(A))
print(np.sum(A,axis=0))
print(np.sum(A, axis=1))

45
[12 15 18]
[ 6 15 24]


In [26]:
print(np.sum(A, axis=0, keepdims=True))
print(np.sum(A, axis=1, keepdims=True))

[[12 15 18]]
[[ 6]
 [15]
 [24]]


In [27]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# for each row sub the max value of that row

# for row in A:
#     mx = np.max(row)
#     row = row - mx

for row_idx in range(len(A)):
    mx = np.max(A[row_idx])
    A[row_idx] -= mx
A

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [ ]:
# not loop based
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A - np.max(A, axis=1)

# the effect of not keeping keepdims 
''' 
it will give us [3,6,9]
and the brodcating will take it 
[3,6,9]
[3,6,9]
[3,6,9]
'''

array([[-2, -4, -6],
       [ 1, -1, -3],
       [ 4,  2,  0]])

In [30]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A - np.max(A, axis=1, keepdims=True)

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])