In [2]:
import numpy as np

In [4]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(A))
print(np.sum(A,axis=0))
print(np.sum(A, axis=1))

45
[12 15 18]
[ 6 15 24]


In [5]:
print(np.sum(A, axis=0, keepdims=True))
print(np.sum(A, axis=1, keepdims=True))

[[12 15 18]]
[[ 6]
 [15]
 [24]]
