In [2]:
import numpy as np

In [3]:
x = np.array([1,2,3])
w = np.array([0.2, .8, -0.5])
b = 2

output = x[0]*w[0] + x[1]*w[1] + x[2]*w[2] + b

print(output)

2.3


In [4]:
input = np.array([1,2,3,2.5])
weight = np.array([0.2, 0.8, -0.5, 1.0])
b = 2


output = input[0]*weight[0] + input[1]*weight[1] + input[2]*weight[2] + input[3]*weight[3]+ b
print(output)


4.8


In [5]:
input =   np.array([1,2,3,2.5])
weights = np.array([ [0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]])

biases = np.array([2, 3, 0.5])


outputs = []

for j in range(3):
    output = sum([input[i]*weights[j,i] for i in range(4)]) + biases[j]
    outputs.append(output)
    print(f"output{j} == {output}")

print(outputs)

output0 == 4.8
output1 == 1.21
output2 == 2.385
[np.float64(4.8), np.float64(1.21), np.float64(2.385)]


In [6]:
# for each neuron; associate the neuron and the bias
for n_weights, n_biases in zip(weights, biases):
    # init the total product sum of the input and its associated weight on the given nuron to 0
    total = 0
    # for each input and its associated weight
    for n_input, weight in zip(input, n_weights):
        total += n_input*weight
    # add the bias term
    total+= n_biases
    print(total)

4.8
1.21
2.385


Numpy approach

In [7]:
input = np.array([1,2,3,2.5])
weight = np.array([0.2, 0.8, -0.5, 1.0])
bias = 2


output = np.dot(input, weight) + bias
output


np.float64(4.8)

In [8]:
input =   np.array([1,2,3,2.5])
weights = np.array([ [0.2, 0.8, -0.5, 1],
            [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]])
biases = np.array([2, 3, 0.5])

outputs = np.dot(weights, input) + biases  # weights, input has to be weights, input.T but due to brodcasting it will compute 3 X 4   X     4 X 4
outputs

array([4.8  , 1.21 , 2.385])

In [9]:
inputs = np.array([[1.0, 2.0, 3.0, 2.5], 
          [2.0, 5.0, -1.0, 2.0], 
          [-1.5, 2.7, 3.3, -0.8]]) # 3 x 4
weights =np.array([[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]) # 3 X 4

biases = np.array([2.0, 3.0, 0.5])

'''
INPUTS; are batch x input features
WEIGHT; features X neurons

the dot product will be INPUTS X WEIGHT.T
'''
outputs = np.dot(inputs, weights.T) + biases 


print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


Adding more layer

In [ ]:
inputs = [[1, 2, 3, 2.5],
          [2., 5., -1., 2],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1],
           [0.5, -0.91, 0.26, -0.5],
           [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
            [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]


input_batch = np.array(inputs)
weights_1 = np.array(weights)
biases_1 = np.array(biases)
weights_2 = np.array(weights2)
biases_2 = np.array(biases2)

# ouput with chain rule
# we will neuron first apprach
outputs = np.dot((np.dot(input_batch, weights_1.T)+biases_1), weights_2.T) + biases_2
'''
This is the same as 
output1 = np.dot(input_batch, weights_1.T)+biases_1
output2 = np.dot(output1, weights_2.T) + biases_2

output2 o output1 (input_batch)
'''


outputs


array([[ 0.5031 , -1.04185, -2.03875],
       [ 0.2434 , -2.7332 , -5.7633 ],
       [-0.99314,  1.41254, -0.35655]])