In [2]:
import numpy as np

In [25]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(np.sum(A))
print(np.sum(A,axis=0))
print(np.sum(A, axis=1))

45
[12 15 18]
[ 6 15 24]


In [26]:
print(np.sum(A, axis=0, keepdims=True))
print(np.sum(A, axis=1, keepdims=True))

[[12 15 18]]
[[ 6]
 [15]
 [24]]


In [27]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
# for each row sub the max value of that row

# for row in A:
#     mx = np.max(row)
#     row = row - mx

for row_idx in range(len(A)):
    mx = np.max(A[row_idx])
    A[row_idx] -= mx
A

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

In [ ]:
# not loop based
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A - np.max(A, axis=1)

# the effect of not keeping keepdims 
''' 
it will give us [3,6,9]
and the brodcating will take it 
[3,6,9]
[3,6,9]
[3,6,9]
'''

array([[-2, -4, -6],
       [ 1, -1, -3],
       [ 4,  2,  0]])

In [32]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

A - np.max(A, axis=1, keepdims=True)

array([[-2, -1,  0],
       [-2, -1,  0],
       [-2, -1,  0]])

ReLu activation 

In [37]:
inputs = [2,-1,0,2,3,-6,-5.1,1.3,6,-6]
output = np.maximum(0, inputs)
output

array([2. , 0. , 0. , 2. , 3. , 0. , 0. , 1.3, 6. , 0. ])

In [46]:
class ReLu_Activation:
    def ReLu_forward(self, input):
        return np.maximum(0, inputs)

In [47]:
from nnfs.datasets import spiral_data
import nnfs

X, y = spiral_data(samples=100, classes=3)

In [50]:
class Layare_Dense(ReLu_Activation):
    def __init__(self, n_input, n_neuron):
        self.weight = 0.1 * np.random.randn(n_input, n_neuron)
        self.bias = np.zeros(n_neuron)
        
    
    def forward(self, input):
        return self.ReLu_forward(np.dot(input, self.weight) + self.bias)

In [51]:
myPerceptron =  Layare_Dense(4,1)
inputs = [-1,2,-5,6]
output = myPerceptron.forward(inputs)
output

array([0, 2, 0, 6])